import { createServer } from 'node:http';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { createCipheriv, createDecipheriv, randomBytes, scrypt as scryptCallback, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';

const scrypt = promisify(scryptCallback);
const env = {
  port: Number(process.env.PORT || 3015),
  baseUrl: (process.env.PUBLIC_BASE_URL || '').replace(/\/$/, ''),
  key: Buffer.from(process.env.APP_ENCRYPTION_KEY || '', 'base64'),
  file: process.env.STATE_PATH || '/var/lib/channel-reposter/app.json',
  legacy: { tg: process.env.TELEGRAM_BOT_TOKEN || '', tgSecret: process.env.TELEGRAM_WEBHOOK_SECRET || '', source: (process.env.TELEGRAM_SOURCE_CHANNEL_USERNAME || '').replace(/^@/, '').toLowerCase(), max: process.env.MAX_BOT_TOKEN || '', maxSecret: process.env.MAX_WEBHOOK_SECRET || '', target: process.env.MAX_TARGET_CHAT_ID || '' },
};
if (env.key.length !== 32) throw new Error('APP_ENCRYPTION_KEY must be a base64-encoded 32-byte key');
if (!env.baseUrl.startsWith('https://')) throw new Error('PUBLIC_BASE_URL must use HTTPS');

let store = { users: [], sessions: [], connections: [], migrated: false };
let writing = Promise.resolve();
const rid = (bytes = 24) => randomBytes(bytes).toString('base64url');
const stamp = () => new Date().toISOString();
const esc = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

function seal(value) { const iv = randomBytes(12), cipher = createCipheriv('aes-256-gcm', env.key, iv), encrypted = Buffer.concat([cipher.update(value, 'utf8'), cipher.final()]); return `${iv.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}.${encrypted.toString('base64url')}`; }
function unseal(value) { const [iv, tag, data] = value.split('.').map((part) => Buffer.from(part, 'base64url')); const decipher = createDecipheriv('aes-256-gcm', env.key, iv); decipher.setAuthTag(tag); return Buffer.concat([decipher.update(data), decipher.final()]).toString('utf8'); }
async function save() { writing = writing.then(async () => { await mkdir('/var/lib/channel-reposter', { recursive: true }); await writeFile(`${env.file}.tmp`, `${JSON.stringify(store, null, 2)}\n`, { mode: 0o600 }); await rename(`${env.file}.tmp`, env.file); }); return writing; }
async function init() { try { store = { ...store, ...JSON.parse(await readFile(env.file, 'utf8')) }; } catch (error) { if (error.code !== 'ENOENT') throw error; } store.users ||= []; store.sessions ||= []; store.connections ||= []; if (!store.migrated && env.legacy.tg && env.legacy.max) { store.connections.push({ id: rid(), userId: null, name: 'Лось в проде', source: env.legacy.source, telegramToken: seal(env.legacy.tg), telegramSecret: env.legacy.tgSecret, maxToken: seal(env.legacy.max), maxSecret: env.legacy.maxSecret, targetChatId: env.legacy.target || null, enabled: true, error: null, createdAt: stamp(), updatedAt: stamp() }); store.migrated = true; await save(); } if (!store.connectionWebhooksMigrated) { for (const connection of store.connections) await tryConfigure(connection); store.connectionWebhooksMigrated = true; await save(); } }

function page(title, content, current) { const nav = current ? `<nav><a href="/dashboard">Подключения</a><form method="post" action="/logout"><input type="hidden" name="csrf" value="${esc(current.session.csrf)}"><button class="link">Выйти</button></form></nav>` : ''; return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Multi Post</title><style>:root{color-scheme:dark;--bg:#080d1d;--card:#111a35;--line:#283963;--text:#edf3ff;--muted:#a9b6d7;--accent:#56d7ff;--violet:#845dff;--ok:#75e6ae;--bad:#ff9dad}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% 0,#1b3270 0,#080d1d 46rem);color:var(--text);font:16px/1.5 Inter,system-ui,sans-serif}.shell{width:min(1040px,calc(100% - 32px));margin:auto}.top{display:flex;justify-content:space-between;align-items:center;padding:24px 0}.brand{font-size:20px;font-weight:800;color:white}.brand b{color:var(--accent)}a{color:var(--accent);text-decoration:none}nav{display:flex;gap:18px;align-items:center}nav form{margin:0}.hero{padding:58px 0 30px;max-width:760px}.hero h1{font-size:clamp(38px,6vw,64px);line-height:1.04;margin:0 0 18px}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{background:#111a35eF;border:1px solid var(--line);border-radius:18px;padding:24px;box-shadow:0 16px 60px #0005}.wide{grid-column:1/-1}.stack{display:grid;gap:14px}.field{display:grid;gap:6px}.field span,.small{font-size:13px;color:var(--muted)}input{width:100%;padding:11px 12px;background:#091127;border:1px solid var(--line);color:var(--text);border-radius:10px;font:inherit}button,.button{border:0;border-radius:10px;background:linear-gradient(120deg,var(--accent),var(--violet));color:#071020;padding:10px 15px;font:inherit;font-weight:750;cursor:pointer;text-decoration:none}.link{padding:0;background:none;color:var(--muted);font-weight:500}.danger{background:transparent;border:1px solid #a6485b;color:#ffc1c9}.row{display:flex;justify-content:space-between;align-items:center;gap:16px}.notice{padding:10px 13px;border-left:3px solid var(--accent);background:#132451;border-radius:6px}.error{border-color:var(--bad);color:#ffdbe0}.ok{color:var(--ok)}.connections{display:grid;gap:14px}@media(max-width:700px){.grid{grid-template-columns:1fr}.wide{grid-column:auto}.row{align-items:flex-start;flex-direction:column}}</style></head><body><div class="shell"><header class="top"><a class="brand" href="/">Multi <b>Post</b></a>${nav}</header>${content}</div></body></html>`; }
function html(response, code, content) { response.writeHead(code, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' }); response.end(content); }
function go(response, location) { response.writeHead(303, { location }); response.end(); }
function cookies(request) { return Object.fromEntries((request.headers.cookie || '').split(';').map((item) => item.trim().split(/=(.*)/s)).filter(([name]) => name)); }
async function raw(request, max = 64 * 1024) { const chunks=[]; let size=0; for await(const chunk of request){size+=chunk.length;if(size>max)throw new Error('Request too large');chunks.push(chunk);}return Buffer.concat(chunks); }
async function form(request) { return Object.fromEntries(new URLSearchParams((await raw(request)).toString())); }
function current(request) { const token=cookies(request).session, session=store.sessions.find((item)=>item.id===token&&item.expiresAt>Date.now()); if(!session)return null; const user=store.users.find((item)=>item.id===session.userId); return user?{user,session}:null; }
function needUser(request,response) { const value=current(request); if(!value)go(response,'/login'); return value; }
function validCsrf(value,data) { return Boolean(value&&data.csrf&&data.csrf.length===value.session.csrf.length&&timingSafeEqual(Buffer.from(data.csrf),Buffer.from(value.session.csrf))); }
async function password(value) { const salt=rid(16); return `scrypt:${salt}:${(await scrypt(value,salt,64)).toString('base64url')}`; }
async function passwordOk(value,stored) { const [,salt,hash]=stored.split(':'); return timingSafeEqual(await scrypt(value,salt,64),Buffer.from(hash,'base64url')); }
async function newSession(userId) { const session={id:rid(32),userId,csrf:rid(24),expiresAt:Date.now()+2_592_000_000};store.sessions=store.sessions.filter((item)=>item.expiresAt>Date.now());store.sessions.push(session);await save();return session; }
function setSession(response,session) { response.setHeader('set-cookie',`session=${session.id}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=2592000`); }

function sourceOk(connection,chat) { return Boolean(chat&&chat.username?.toLowerCase()===connection.source); }
function textOf(message) { return message.caption || message.text || ''; }
function tagsOf(message) { return message.caption_entities || message.entities || []; }
function validUrl(url) { try { return ['http:','https:','tg:','mailto:','tel:'].includes(new URL(url).protocol) ? url : null; } catch { return null; } }
function tag(entity,text) { const href=entity.type==='text_link'?validUrl(entity.url||''):entity.type==='url'?validUrl(text):null; if(href)return [`<a href="${esc(href)}">`,'</a>']; const map={bold:['<b>','</b>'],italic:['<i>','</i>'],underline:['<u>','</u>'],strikethrough:['<s>','</s>'],code:['<code>','</code>'],pre:['<pre>','</pre>'],email:[`<a href="mailto:${esc(text)}">`,'</a>'],phone_number:[`<a href="tel:${esc(text)}">`,'</a>']};return map[entity.type]||null; }
function formatTelegram(text,entities) { const valid=entities.filter((item)=>Number.isInteger(item.offset)&&Number.isInteger(item.length)&&item.length>0&&item.offset>=0&&item.offset+item.length<=text.length).sort((a,b)=>a.offset-b.offset||b.length-a.length);if(!valid.length)return null;const points=[...new Set([0,text.length,...valid.flatMap((item)=>[item.offset,item.offset+item.length])])].sort((a,b)=>a-b);let used=false,result='';for(let i=0;i<points.length-1;i+=1){const start=points[i],end=points[i+1],active=valid.filter((item)=>item.offset<=start&&item.offset+item.length>=end).map((item)=>tag(item,text.slice(item.offset,item.offset+item.length))).filter(Boolean);let part=esc(text.slice(start,end));for(let j=active.length-1;j>=0;j-=1)part=`${active[j][0]}${part}${active[j][1]}`;used ||= active.length>0;result+=part;}return used?result:null; }
function split(text) { if(!text)return [''];const result=[];let rest=text;while(rest.length>4000){const end=Math.max(rest.lastIndexOf('\n',4000),rest.lastIndexOf(' ',4000),4000);result.push(rest.slice(0,end).trimEnd());rest=rest.slice(end).trimStart();}result.push(rest);return result; }
function fileOf(message) { if(message.photo?.length){const photo=message.photo.at(-1);return {type:'image',id:photo.file_id,name:'telegram-photo.jpg',mime:'image/jpeg'};}if(message.video)return {type:'video',id:message.video.file_id,name:message.video.file_name||'telegram-video.mp4',mime:message.video.mime_type||'video/mp4'};if(message.animation)return {type:'video',id:message.animation.file_id,name:message.animation.file_name||'telegram-animation.mp4',mime:message.animation.mime_type||'video/mp4'};if(message.audio)return {type:'audio',id:message.audio.file_id,name:message.audio.file_name||'telegram-audio.mp3',mime:message.audio.mime_type||'audio/mpeg'};if(message.voice)return {type:'audio',id:message.voice.file_id,name:'telegram-voice.ogg',mime:message.voice.mime_type||'audio/ogg'};if(message.document)return {type:'file',id:message.document.file_id,name:message.document.file_name||'telegram-file',mime:message.document.mime_type||'application/octet-stream'};return null; }
async function upload(connection,item) { const tg=unseal(connection.telegramToken),max=unseal(connection.maxToken),info=await (await fetch(`https://api.telegram.org/bot${tg}/getFile?file_id=${encodeURIComponent(item.id)}`)).json();if(!info.ok||!info.result?.file_path)throw new Error('Telegram file is unavailable');const source=await fetch(`https://api.telegram.org/file/bot${tg}/${info.result.file_path}`);const endpoint=await fetch(`https://platform-api2.max.ru/uploads?type=${item.type}`,{method:'POST',headers:{Authorization:max}}),address=await endpoint.json();if(!endpoint.ok||!address.url)throw new Error('MAX upload URL failed');const data=new FormData();data.append('data',new Blob([await source.arrayBuffer()],{type:item.mime}),item.name);const response=await fetch(address.url,{method:'POST',body:data}),text=await response.text();if(!response.ok)throw new Error('MAX media upload failed');let answer={};try{answer=JSON.parse(text);}catch{}const token=answer.token||address.token;if(!token)throw new Error('MAX upload returned no token');return {type:item.type,payload:{token}}; }
async function repost(connection,message) { if(!connection.targetChatId)throw new Error('MAX channel has not been connected');const original=textOf(message),formatted=formatTelegram(original,tagsOf(message)),useHtml=Boolean(formatted&&formatted.length<=4000),parts=useHtml?[formatted]:split(original),item=fileOf(message),attachment=item?await upload(connection,item):null,max=unseal(connection.maxToken);for(let i=0;i<parts.length;i+=1){const payload={text:parts[i],notify:true};if(useHtml)payload.format='html';if(i===0&&attachment)payload.attachments=[attachment];const response=await fetch(`https://platform-api2.max.ru/messages?chat_id=${encodeURIComponent(connection.targetChatId)}`,{method:'POST',headers:{Authorization:max,'content-type':'application/json'},body:JSON.stringify(payload)});if(!response.ok)throw new Error(`MAX rejected the post (${response.status})`);} }
async function configure(connection) { const tg=unseal(connection.telegramToken),max=unseal(connection.maxToken);const telegram=await (await fetch(`https://api.telegram.org/bot${tg}/setWebhook`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:`${env.baseUrl}/webhooks/telegram/${connection.id}`,secret_token:connection.telegramSecret,allowed_updates:['channel_post']})})).json();if(!telegram.ok)throw new Error('Telegram rejected this bot token');const result=await (await fetch('https://platform-api2.max.ru/subscriptions',{method:'POST',headers:{Authorization:max,'content-type':'application/json'},body:JSON.stringify({url:`${env.baseUrl}/webhooks/max/${connection.id}`,update_types:['bot_added','bot_removed'],secret:connection.maxSecret})})).json();if(!result.success)throw new Error('MAX rejected this bot token');connection.error=null;connection.updatedAt=stamp();await save(); }
async function tryConfigure(connection){try{await configure(connection);}catch(error){connection.error=error.message;connection.updatedAt=stamp();await save();}}

function dashboard(value,notice='') { const list=store.connections.filter((item)=>item.userId===value.user.id); const cards=list.length?list.map((item)=>`<article class="card"><div class="row"><div><h3>${esc(item.name)}</h3><p class="small">Telegram: @${esc(item.source)} → MAX: ${item.targetChatId?'<span class="ok">подключён</span>':'ожидает канал'}</p></div><form method="post" action="/connections/${item.id}/toggle"><input type="hidden" name="csrf" value="${esc(value.session.csrf)}"><button class="${item.enabled?'danger':''}">${item.enabled?'Отключить':'Включить'}</button></form></div>${item.error?`<p class="notice error small">${esc(item.error)}</p>`:''}<p class="small muted">Токены зашифрованы и не показываются. ${item.targetChatId?'Новые посты репостятся автоматически.':'После сохранения добавьте MAX-бота в целевой канал администратором.'}</p><form method="post" action="/connections/${item.id}/configure"><input type="hidden" name="csrf" value="${esc(value.session.csrf)}"><button>Переустановить webhook</button></form></article>`).join(''):'<p class="muted">Подключений ещё нет.</p>';return page('Подключения',`<main><div class="hero"><h1>Управляйте своими<br>репостами.</h1><p class="muted">Каждая связка Telegram → MAX изолирована и доступна только её владельцу.</p>${notice?`<p class="notice">${esc(notice)}</p>`:''}</div><section class="grid"><article class="card wide"><h2>Мои подключения</h2><div class="connections">${cards}</div></article><article class="card wide"><h2>Новое подключение</h2><p class="small muted">Добавьте Telegram-бота администратором исходного канала. После сохранения добавьте MAX-бота администратором целевого канала — его ID определится автоматически.</p><form class="stack" method="post" action="/connections"><input type="hidden" name="csrf" value="${esc(value.session.csrf)}"><div class="grid"><label class="field"><span>Название</span><input name="name" maxlength="80" required placeholder="Новости компании"></label><label class="field"><span>Исходный Telegram-канал</span><input name="source" maxlength="64" required placeholder="@my_channel"></label><label class="field"><span>Токен Telegram-бота</span><input name="telegramToken" type="password" autocomplete="off" required></label><label class="field"><span>Токен MAX-бота</span><input name="maxToken" type="password" autocomplete="off" required></label><label class="field"><span>ID канала MAX (необязательно)</span><input name="targetChatId" placeholder="Оставьте пустым для автоопределения"></label></div><button>Создать подключение</button></form></article></section></main>`,value); }
function auth(kind,message='') { const register=kind==='register';return page(register?'Регистрация':'Вход',`<main class="hero"><h1>${register?'Создайте кабинет':'Войдите в кабинет'}</h1><p class="muted">Токены ботов сохраняются только в зашифрованном виде.</p><section class="card" style="max-width:500px"><form class="stack" method="post" action="/${kind}">${message?`<p class="notice error">${esc(message)}</p>`:''}<label class="field"><span>E-mail</span><input name="email" type="email" autocomplete="email" required></label><label class="field"><span>Пароль</span><input name="password" type="password" minlength="10" autocomplete="${register?'new-password':'current-password'}" required></label><button>${register?'Зарегистрироваться':'Войти'}</button></form><p class="small muted">${register?'Уже есть аккаунт? <a href="/login">Войти</a>':'Нет аккаунта? <a href="/register">Зарегистрироваться</a>'}</p></section></main>`); }

const server=createServer(async(request,response)=>{const url=new URL(request.url,`http://${request.headers.host||'localhost'}`);try{
  if(request.method==='POST'&&url.pathname.startsWith('/webhooks/telegram/')){const connection=store.connections.find((item)=>item.id===url.pathname.split('/').at(-1));if(!connection||request.headers['x-telegram-bot-api-secret-token']!==connection.telegramSecret){response.writeHead(401);return response.end();}const update=JSON.parse((await raw(request,2*1024*1024)).toString());if(connection.enabled&&update.channel_post&&sourceOk(connection,update.channel_post.chat))await repost(connection,update.channel_post);response.writeHead(200);return response.end();}
  if(request.method==='POST'&&url.pathname.startsWith('/webhooks/max/')){const connection=store.connections.find((item)=>item.id===url.pathname.split('/').at(-1));if(!connection||request.headers['x-max-bot-api-secret']!==connection.maxSecret){response.writeHead(401);return response.end();}const update=JSON.parse((await raw(request,2*1024*1024)).toString());if(update.update_type==='bot_added'&&update.is_channel&&update.chat_id){connection.targetChatId=String(update.chat_id);connection.error=null;connection.updatedAt=stamp();await save();}response.writeHead(200);return response.end();}
  if(request.method==='GET'&&url.pathname==='/healthz'){response.writeHead(200,{'content-type':'application/json'});return response.end(JSON.stringify({ok:true,users:store.users.length,connections:store.connections.length,active:store.connections.filter((item)=>item.enabled&&item.targetChatId).length}));}
  if(request.method==='GET'&&url.pathname==='/'){const value=current(request);return html(response,200,page('Автопостинг',`<main class="hero"><h1>Репосты между<br><span style="color:var(--accent)">Telegram и MAX</span>.</h1><p class="muted">Подключайте собственные каналы без доступа к чужим настройкам.</p><a class="button" href="${value?'/dashboard':'/register'}">${value?'Открыть кабинет':'Создать аккаунт'}</a></main>`,value));}
  if(request.method==='GET'&&url.pathname==='/register')return html(response,200,auth('register'));
  if(request.method==='POST'&&url.pathname==='/register'){const data=await form(request),email=(data.email||'').trim().toLowerCase(),pass=data.password||'';if(!/^\S+@\S+\.\S+$/.test(email)||pass.length<10)return html(response,400,auth('register','Введите корректный e-mail и пароль от 10 символов.'));if(store.users.some((item)=>item.email===email))return html(response,409,auth('register','Этот e-mail уже зарегистрирован.'));const user={id:rid(),email,passwordHash:await password(pass),createdAt:stamp()};store.users.push(user);for(const connection of store.connections)if(connection.userId===null)connection.userId=user.id;const session=await newSession(user.id);setSession(response,session);return go(response,'/dashboard');}
  if(request.method==='GET'&&url.pathname==='/login')return html(response,200,auth('login'));
  if(request.method==='POST'&&url.pathname==='/login'){const data=await form(request),user=store.users.find((item)=>item.email===(data.email||'').trim().toLowerCase());if(!user||!await passwordOk(data.password||'',user.passwordHash))return html(response,401,auth('login','Неверный e-mail или пароль.'));const session=await newSession(user.id);setSession(response,session);return go(response,'/dashboard');}
  if(request.method==='POST'&&url.pathname==='/logout'){const value=needUser(request,response);if(!value)return;const data=await form(request);if(!validCsrf(value,data))return html(response,403,page('Ошибка','<p>Недействительная форма.</p>'));store.sessions=store.sessions.filter((item)=>item.id!==value.session.id);await save();response.setHeader('set-cookie','session=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0');return go(response,'/');}
  if(request.method==='GET'&&url.pathname==='/dashboard'){const value=needUser(request,response);if(value)return html(response,200,dashboard(value));return;}
  if(request.method==='POST'&&url.pathname==='/connections'){const value=needUser(request,response);if(!value)return;const data=await form(request);if(!validCsrf(value,data))return html(response,403,page('Ошибка','<p>Недействительная форма.</p>'));const source=(data.source||'').replace(/^@/,'').trim().toLowerCase();if(!/^[a-zA-Z0-9_]{5,64}$/.test(source)||!(data.telegramToken||'').trim()||!(data.maxToken||'').trim())return html(response,400,dashboard(value,'Проверьте название канала и оба токена.'));if(store.connections.some((item)=>item.source===source&&item.enabled))return html(response,409,dashboard(value,'Этот Telegram-канал уже подключён.'));const connection={id:rid(),userId:value.user.id,name:(data.name||'Новый канал').trim().slice(0,80),source,telegramToken:seal(data.telegramToken.trim()),telegramSecret:rid(32),maxToken:seal(data.maxToken.trim()),maxSecret:rid(32),targetChatId:(data.targetChatId||'').trim()||null,enabled:true,error:null,createdAt:stamp(),updatedAt:stamp()};store.connections.push(connection);await save();await tryConfigure(connection);return go(response,'/dashboard');}
  const matched=url.pathname.match(/^\/connections\/([^/]+)\/(toggle|configure)$/);if(request.method==='POST'&&matched){const value=needUser(request,response);if(!value)return;const data=await form(request),connection=store.connections.find((item)=>item.id===matched[1]&&item.userId===value.user.id);if(!connection||!validCsrf(value,data))return html(response,403,page('Ошибка','<p>Нет доступа.</p>'));if(matched[2]==='toggle'){connection.enabled=!connection.enabled;connection.updatedAt=stamp();await save();}else await tryConfigure(connection);return go(response,'/dashboard');}
  return html(response,404,page('Не найдено','<main class="hero"><h1>Страница не найдена</h1></main>'));
}catch(error){console.error(error);return html(response,500,page('Ошибка','<main class="hero"><h1>Не удалось выполнить действие</h1><p class="muted">Проверьте данные и повторите.</p></main>'));}});

await init();
server.listen(env.port,'127.0.0.1',()=>console.log(`Multi Post is listening on 127.0.0.1:${env.port}`));
